### ISSUE TITLE
4.9内核无法make

### ISSUE THREAD

**Issue by mhlau233** [fifilyu/module-http-whitelist#2]
make -C /lib/modules/4.9.0-rc8-amd64/build/ M=/root/module-http-whitelist modules
make: *** /lib/modules/4.9.0-rc8-amd64/build/: No such file or directory.  Stop.
make: *** [all] Error 2

**Comment by fifilyu** [comment]
看样子你是在自定义内核的系统上编译的。
这不是代码错误，你提供的错误信息中已经明确提示缺少“ /lib/modules/4.9.0-rc8-amd64/build/” 目录。
看样子你是没安装4.9.0-rc8的内核开发包导致的问题。

**Comment by alensent** [comment]
我的问题和这个差不多，先是内核版本和开发包版本不一致（独立升级过内核），还原之前的内核版本登录后，还是有make的报错。

```
[root@gs-server-xxxx module-http-whitelist]# make
make -C /lib/modules/3.10.0-693.21.1.el7.x86_64/build/ M=/root/module-http-whitelist modules
make[1]: 进入目录“/usr/src/kernels/3.10.0-693.21.1.el7.x86_64”
make[1]: *** 没有规则可以创建目标“modules”。 停止。
make[1]: 离开目录“/usr/src/kernels/3.10.0-693.21.1.el7.x86_64”
make: *** [all] 错误 2
[root@gs-server-xxxx module-http-whitelist]# 
```

**Comment by fifilyu** [comment]
> 我的问题和这个差不多，先是内核版本和开发包版本不一致（独立升级过内核），还原之前的内核版本登录后，还是有make的报错。
> 
> ```
> [root@gs-server-xxxx module-http-whitelist]# make
> make -C /lib/modules/3.10.0-693.21.1.el7.x86_64/build/ M=/root/module-http-whitelist modules
> make[1]: 进入目录“/usr/src/kernels/3.10.0-693.21.1.el7.x86_64”
> make[1]: *** 没有规则可以创建目标“modules”。 停止。
> make[1]: 离开目录“/usr/src/kernels/3.10.0-693.21.1.el7.x86_64”
> make: *** [all] 错误 2
> [root@gs-server-xxxx module-http-whitelist]# 
> ```

你可以单独提一个issue吗？
